# Generated by Django 4.0.2 on 2022-02-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monarch', '0004_alter_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.TextField(default='Other'),
            preserve_default=False,
        ),
    ]
