# Generated by Django 4.0.2 on 2022-02-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monarch', '0005_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.TextField(choices=[('credit_card', 'credit_card'), ('checking', 'checking'), ('savings', 'savings')], null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.TextField(choices=[('income', 'income'), ('expense', 'expense'), ('tranfer', 'tranfer')]),
        ),
    ]
